ERROR - 2022-09-16 15:17:10 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'projetobancotest' in C:\xampp\htdocs\site1\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\site1\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'projetobancotes...', 3306, '', 0)
#1 C:\xampp\htdocs\site1\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\site1\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\site1\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\site1\system\Model.php(222): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\site1\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\site1\app\Controllers\Animal.php(17): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\site1\system\CodeIgniter.php(898): App\Controllers\Animal->index()
#8 C:\xampp\htdocs\site1\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Animal))
#9 C:\xampp\htdocs\site1\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\site1\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'projetobancotest' in C:\xampp\htdocs\site1\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\site1\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\site1\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\site1\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\site1\system\Model.php(222): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\site1\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\site1\app\Controllers\Animal.php(17): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\site1\system\CodeIgniter.php(898): App\Controllers\Animal->index()
#7 C:\xampp\htdocs\site1\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Animal))
#8 C:\xampp\htdocs\site1\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\site1\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-09-16 15:17:10 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'projetobancotest'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cadastro_animal`', [], false)
 3 SYSTEMPATH\Model.php(222): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Animal.php(17): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Animal->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Animal))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
